<Project Sdk="Microsoft.NET.Sdk">
	<PropertyGroup>
		<OutputType>WinExe</OutputType>
		<AssemblyName>xRateExt</AssemblyName>
		<RootNamespace>xRateExt</RootNamespace>
		<ApplicationManifest>app.manifest</ApplicationManifest>
		<WindowsSdkPackageVersion>10.0.26100.69</WindowsSdkPackageVersion>
		<TargetFramework>net9.0-windows10.0.26100.0</TargetFramework>
		<TargetPlatformMinVersion>10.0.19041.0</TargetPlatformMinVersion>
		<SupportedOSPlatformVersion>10.0.19041.0</SupportedOSPlatformVersion>
		<Platforms>x64;ARM64</Platforms>
		<RuntimeIdentifiers>win-x64;win-arm64</RuntimeIdentifiers>
		<RuntimeIdentifier Condition="'$(Platform)' == 'x64'">win-x64</RuntimeIdentifier>
		<RuntimeIdentifier Condition="'$(Platform)' == 'ARM64'">win-arm64</RuntimeIdentifier>
		<SelfContained>true</SelfContained>
		<PublishProfile>win-$(Platform).pubxml</PublishProfile>
		<EnableMsixTooling>true</EnableMsixTooling>
		<AppxPackage>true</AppxPackage>
		<Nullable>enable</Nullable>
		<WindowsAppSDKSelfContained>true</WindowsAppSDKSelfContained>
		<WindowsPackageType>MSIX</WindowsPackageType>
		<AppxPackageIdentityName>OthmanAMOR.xRate-CommandPaletteExtension</AppxPackageIdentityName>
		<AppxPackagePublisher>CN=CA938298-1CC2-4C29-B546-D8367F20D6A1</AppxPackagePublisher>
		<AppxPackageVersion>1.0.2.0</AppxPackageVersion>
	</PropertyGroup>

	<ItemGroup>
		<Manifest Include="$(ApplicationManifest)" />
	</ItemGroup>

	<ItemGroup>
		<ProjectCapability Include="Msix" />
	</ItemGroup>

	<ItemGroup>
		<PackageReference Include="Microsoft.CommandPalette.Extensions" />
		<PackageReference Include="Microsoft.WindowsAppSDK" />
		<PackageReference Include="Microsoft.Windows.CsWinRT" />
		<PackageReference Include="Shmuelie.WinRTServer" />
		<PackageReference Include="Microsoft.Windows.SDK.BuildTools">
			<PrivateAssets>all</PrivateAssets>
			<IncludeAssets>runtime; build; native; contentfiles; analyzers</IncludeAssets>
		</PackageReference>
	</ItemGroup>

	<ItemGroup>
		<ProjectReference Include="..\xRate.Core\xRate.Core.csproj" />
	</ItemGroup>

	<ItemGroup>
		<Content Include="Assets\**\*.png" />
	</ItemGroup>

	<Target Name="PrepareAssets" BeforeTargets="BeforeBuild">
		<Copy SourceFiles="$(MSBuildProjectDirectory)\Assets\Square150x150Logo.scale-200.png" DestinationFiles="$(MSBuildProjectDirectory)\Assets\Square150x150Logo.png" SkipUnchangedFiles="true" />
		<Copy SourceFiles="$(MSBuildProjectDirectory)\Assets\Square44x44Logo.scale-200.png" DestinationFiles="$(MSBuildProjectDirectory)\Assets\SmallTile.png" SkipUnchangedFiles="true" />
		<Copy SourceFiles="$(MSBuildProjectDirectory)\Assets\WideTile.scale-200.png" DestinationFiles="$(MSBuildProjectDirectory)\Assets\WideTile.png" SkipUnchangedFiles="true" />
		<Copy SourceFiles="$(MSBuildProjectDirectory)\Assets\SplashScreen.scale-200.png" DestinationFiles="$(MSBuildProjectDirectory)\Assets\SplashScreen.png" SkipUnchangedFiles="true" />
		<Copy SourceFiles="$(MSBuildProjectDirectory)\Assets\LargeTile.scale-200.png" DestinationFiles="$(MSBuildProjectDirectory)\Assets\LargeTile.png" SkipUnchangedFiles="true" />
		<Copy SourceFiles="$(MSBuildProjectDirectory)\Assets\StoreLogo.scale-100.png" DestinationFiles="$(MSBuildProjectDirectory)\Assets\StoreLogo.png" SkipUnchangedFiles="true" />
	</Target>

	<PropertyGroup>
		<HasPackageAndPublishMenu>true</HasPackageAndPublishMenu>
	</PropertyGroup>

	<PropertyGroup>
		<IsAotCompatible>true</IsAotCompatible>
		<CsWinRTAotOptimizerEnabled>true</CsWinRTAotOptimizerEnabled>
		<CsWinRTAotWarningLevel>2</CsWinRTAotWarningLevel>
		<WarningsNotAsErrors>IL2081;$(WarningsNotAsErrors)</WarningsNotAsErrors>
		<ILLinkTreatWarningsAsErrors>true</ILLinkTreatWarningsAsErrors>
		<DefaultLanguage>en</DefaultLanguage>
		<GenerateAppInstallerFile>False</GenerateAppInstallerFile>
		<AppxPackageSigningEnabled>False</AppxPackageSigningEnabled>
		<AppxPackageSigningTimestampDigestAlgorithm>SHA256</AppxPackageSigningTimestampDigestAlgorithm>
		<AppxAutoIncrementPackageRevision>False</AppxAutoIncrementPackageRevision>
		<AppxSymbolPackageEnabled>False</AppxSymbolPackageEnabled>
		<GenerateTestArtifacts>True</GenerateTestArtifacts>
		<AppxBundle>Always</AppxBundle>
		<HoursBetweenUpdateChecks>0</HoursBetweenUpdateChecks>
		<AppxBundlePlatforms>x64|arm64</AppxBundlePlatforms>
	</PropertyGroup>

	<PropertyGroup Condition="'$(Configuration)'=='Debug'">
		<PublishTrimmed>false</PublishTrimmed>
		<EnableTrimAnalyzer>true</EnableTrimAnalyzer>
		<EnableSingleFileAnalyzer>true</EnableSingleFileAnalyzer>
		<EnableAotAnalyzer>true</EnableAotAnalyzer>
		<PublishSingleFile>false</PublishSingleFile>
	</PropertyGroup>

	<PropertyGroup Condition="'$(Configuration)'!='Debug'">
		<PublishTrimmed>false</PublishTrimmed>
		<PublishSingleFile>false</PublishSingleFile>
		<ILLinkTreatWarningsAsErrors>false</ILLinkTreatWarningsAsErrors>
	</PropertyGroup>
</Project>